import type { WizardData } from "../BootstrapWizard";
import { Icon } from "../../../components/ui/Icon";
import { ValidationItem } from "../components/ValidationItem";
import { buildTopologyGraph } from "../topology";

type ReviewWriteProps = {
  data: WizardData;
  onChange: (partial: Partial<WizardData>) => void;
  onRequestAiRound?: () => Promise<void> | void;
  isAiGenerating?: boolean;
  onWriteConfiguration?: (yamlContent: string) => Promise<void> | void;
  isWritingConfiguration?: boolean;
  writeResult?: { ok: boolean; message: string } | null;
};

function generateYaml(data: WizardData): string {
  const topology = buildTopologyGraph(data);
  const crewId = data.crewId || "dev";
  const mission = data.missionStatement || "TBD";
  const description = data.description || "";
  const projectName = data.projectName || "my-project";
  const model = data.model || "glm-4.7";

  const leads: string[] = [];
  const workersByTeam: Record<string, string[]> = {};
  const agents: string[] = [];

  topology.teams.forEach((team) => {
    const teamId = team.id;
    workersByTeam[teamId] = [];
    team.agents.forEach((agent) => {
      agents.push(agent.name);
      if (agent.role === "lead") leads.push(`        ${teamId}: ${agent.name}`);
      else workersByTeam[teamId].push(agent.name);
    });
  });

  const workerLines: string[] = [];
  Object.entries(workersByTeam).forEach(([teamId, names]) => {
    workerLines.push(`        ${teamId}:`);
    names.forEach((name) => workerLines.push(`          - ${name}`));
  });

  const agentEntries = agents.map((agentId) => {
    const isLead = leads.some((line) => line.endsWith(`: ${agentId}`));
    const team = topology.teams.find((item) => item.agents.some((a) => a.name === agentId))?.id || "general";
    return [
      "      - id: " + agentId,
      "        role: " + (isLead ? "lead" : "worker"),
      "        team: " + team,
      "        model_ref: " + (isLead ? "lead_default" : "worker_default"),
      "        expertise: " + `${agentId}-expertise-model`,
      "        skills: [expertise_model]",
      "        domain_profile: read_only_cwd",
    ].join("\n");
  });

  return [
    "version: 1",
    "name: " + projectName,
    "description: " + (description || "Bootstrap configuration generated by MAH setup."),
    "runtimes:",
    "  pi: {}",
    "  claude: {}",
    "  opencode: {}",
    "  openclaude: {}",
    "  hermes: {}",
    "  kilo: {}",
    "  codex: {}",
    "",
    "catalog:",
    "  models:",
    `    orchestrator_default: ${model}`,
    `    lead_default: ${model}`,
    `    worker_default: ${model}`,
    `    qa_default: ${model}`,
    "domain_profiles:",
    "  read_only_cwd:",
    "    - path: .",
    "      read: true",
    "",
    "crews:",
    `  - id: ${crewId}`,
    `    display_name: ${crewId === "dev" ? "Development Crew" : `${crewId} Crew`}`,
    `    mission: "${mission}"`,
    "    topology:",
    `      orchestrator: ${topology.orchestrator.name}`,
    "      leads:",
    ...leads,
    "      workers:",
    ...workerLines,
    "    agents:",
    ...agentEntries,
    "",
  ].join("\n").trim();
}

export function ReviewWrite({
  data,
  onChange,
  onRequestAiRound,
  isAiGenerating = false,
  onWriteConfiguration,
  isWritingConfiguration = false,
  writeResult = null,
}: ReviewWriteProps) {
  const yamlContent = generateYaml(data);
  const checks = [
    { status: "check" as const, text: "Project name defined" },
    {
      status: data.crewId ? ("check" as const) : ("warning" as const),
      text: data.crewId ? "Crew ID set" : "Crew ID not set (will use default)",
    },
    {
      status: data.setupMode ? ("check" as const) : ("warning" as const),
      text: data.setupMode ? "Setup mode selected" : "No setup mode selected",
    },
    {
      status: data.provider ? ("check" as const) : ("warning" as const),
      text: data.provider ? "Provider: " + data.provider : "No provider selected",
    },
    {
      status: data.runtime ? ("check" as const) : ("warning" as const),
      text: data.runtime ? "Runtime: " + data.runtime : "No runtime selected",
    },
  ];

  return (
    <div className="wizard-step">
      <h3 className="wizard-step__title">Review &amp; Write</h3>
      <p className="wizard-step__desc">
        Review the generated configuration before writing to disk.
      </p>
      <div className="yaml-preview">
        <div className="yaml-preview__header">
          <span>meta-agents.yaml</span>
        </div>
        <pre className="yaml-preview__code">
          <code>{yamlContent}</code>
        </pre>
      </div>
      <ul className="validation-list">
        {checks.map((c) => (
          <ValidationItem key={c.text} status={c.status} text={c.text} />
        ))}
      </ul>
      <div className="wizard-warning-box">
        <Icon name="warning" size={16} />
        <p>
          This will create or overwrite <code>meta-agents.yaml</code> in your project root.
          Make sure you have a backup of any existing configuration.
        </p>
      </div>
      {data.setupMode === "ai-assisted" ? (
        <div className="form-field form-field--full wizard-review-prompt">
          {data.topologyAiMode === "fallback" ? (
            <div className="wizard-info-box topology-ai-fallback">
              <span className="material-symbols-outlined">info</span>
              <span>
                {data.topologyAiError
                  ? `Current topology came from fallback mode. ${data.topologyAiError}`
                  : "Current topology came from fallback mode. Add provider/model/API key to enable full AI-assisted generation."}
              </span>
            </div>
          ) : null}
          <label className="form-label" htmlFor="topology-review-prompt">Review Prompt (next round)</label>
          <textarea
            id="topology-review-prompt"
            className="form-textarea"
            rows={3}
            placeholder="Refine team structure, naming, and worker distribution..."
            value={data.topologyReviewPrompt || ""}
            onChange={(event) => onChange({ topologyReviewPrompt: event.target.value })}
          />
          <button
            type="button"
            className="wizard-nav__btn wizard-nav__btn--next"
            disabled={isAiGenerating}
            onClick={() => onRequestAiRound?.()}
          >
            <Icon name={isAiGenerating ? "autorenew" : "psychology"} size={16} className={isAiGenerating ? "wizard-spin" : ""} />
            {isAiGenerating ? "Working..." : "Run Next Round"}
          </button>
        </div>
      ) : null}
      <label className="wizard-confirm">
        <input
          type="checkbox"
          checked={data.confirmed ?? false}
          onChange={(e) => onChange({ confirmed: e.target.checked })}
        />
        <span>I have reviewed the configuration and understand the changes</span>
      </label>
      <button
        className="wizard-write-btn"
        type="button"
        disabled={!data.confirmed || isWritingConfiguration}
        onClick={() => onWriteConfiguration?.(yamlContent)}
      >
        <Icon name={isWritingConfiguration ? "autorenew" : "save"} size={18} className={isWritingConfiguration ? "wizard-spin" : ""} />
        {isWritingConfiguration ? "Writing..." : "Write Configuration"}
      </button>
      {writeResult ? (
        <p className={`wizard-write-feedback ${writeResult.ok ? "wizard-write-feedback--ok" : "wizard-write-feedback--error"}`}>
          {writeResult.message}
        </p>
      ) : null}
    </div>
  );
}
