import type { WizardData } from "../BootstrapWizard";
import { Icon } from "../../../components/ui/Icon";
import { ValidationItem } from "../components/ValidationItem";

type ReviewWriteProps = {
  data: WizardData;
  onChange: (partial: Partial<WizardData>) => void;
};

function generateYaml(data: WizardData): string {
  return [
    "# MAH Configuration - generated by Bootstrap Wizard",
    "project:",
    "  name: " + (data.projectName || "my-project"),
    "  crew: " + (data.crewId || "dev"),
    '  mission: "' + (data.missionStatement || "TBD") + '"',
    '  description: "' + (data.description || "") + '"',
    "  runtime: " + (data.runtime || ".pi/"),
    "",
    "provider:",
    "  name: " + (data.provider || "zai"),
    "  model: " + (data.model || "glm-4.7"),
    "  mode: " + (data.setupMode || "logical"),
    "",
    "topology:",
    "  orchestrator:",
    "    name: Orchestrator",
    "    model: ${provider.model}",
    "  teams:",
    "    - name: Planning",
    "      agents:",
    "        - { name: planning-lead, role: lead }",
    "        - { name: backlog-groomer, role: worker }",
    "    - name: Engineering",
    "      agents:",
    "        - { name: engineering-lead, role: lead }",
    "        - { name: frontend-dev, role: worker }",
    "        - { name: backend-dev, role: worker }",
    "    - name: Validation",
    "      agents:",
    "        - { name: qa-lead, role: lead }",
    "        - { name: test-runner, role: worker }",
  ].join("\n");
}

export function ReviewWrite({ data, onChange }: ReviewWriteProps) {
  const checks = [
    { status: "check" as const, text: "Project name defined" },
    {
      status: data.crewId ? ("check" as const) : ("warning" as const),
      text: data.crewId ? "Crew ID set" : "Crew ID not set (will use default)",
    },
    {
      status: data.setupMode ? ("check" as const) : ("warning" as const),
      text: data.setupMode ? "Setup mode selected" : "No setup mode selected",
    },
    {
      status: data.provider ? ("check" as const) : ("warning" as const),
      text: data.provider ? "Provider: " + data.provider : "No provider selected",
    },
    {
      status: data.runtime ? ("check" as const) : ("warning" as const),
      text: data.runtime ? "Runtime: " + data.runtime : "No runtime selected",
    },
  ];

  return (
    <div className="wizard-step">
      <h3 className="wizard-step__title">Review &amp; Write</h3>
      <p className="wizard-step__desc">
        Review the generated configuration before writing to disk.
      </p>
      <div className="yaml-preview">
        <div className="yaml-preview__header">
          <span>meta-agents.yaml</span>
        </div>
        <pre className="yaml-preview__code">
          <code>{generateYaml(data)}</code>
        </pre>
      </div>
      <ul className="validation-list">
        {checks.map((c) => (
          <ValidationItem key={c.text} status={c.status} text={c.text} />
        ))}
      </ul>
      <div className="wizard-warning-box">
        <Icon name="warning" size={16} />
        <p>
          This will create or overwrite <code>meta-agents.yaml</code> in your project root.
          Make sure you have a backup of any existing configuration.
        </p>
      </div>
      <label className="wizard-confirm">
        <input
          type="checkbox"
          checked={data.confirmed ?? false}
          onChange={(e) => onChange({ confirmed: e.target.checked })}
        />
        <span>I have reviewed the configuration and understand the changes</span>
      </label>
      <button
        className="wizard-write-btn"
        type="button"
        disabled={!data.confirmed}
      >
        <Icon name="save" size={18} />
        Write Configuration
      </button>
    </div>
  );
}
