import test from "node:test"
import assert from "node:assert/strict"
import { mkdtempSync, mkdirSync, writeFileSync } from "node:fs"
import os from "node:os"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { RUNTIME_ADAPTERS, RUNTIME_ORDER, createAdapter } from "../scripts/runtime-adapters.mjs"
import { validateRuntimeAdapterContract, REQUIRED_RUNTIME_COMMANDS } from "../scripts/runtime-adapter-contract.mjs"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const repoRoot = path.resolve(__dirname, "..")

test("runtime adapters satisfy minimal contract", () => {
  const result = validateRuntimeAdapterContract(RUNTIME_ADAPTERS)
  assert.equal(result.ok, true, result.errors.join("\n"))
})

test("hermes adapter exists in RUNTIME_ORDER", () => {
  assert.ok(RUNTIME_ORDER.includes("hermes"), "hermes must be in RUNTIME_ORDER")
})

test("hermes adapter exists in RUNTIME_ADAPTERS", () => {
  assert.ok("hermes" in RUNTIME_ADAPTERS, "hermes must be a key in RUNTIME_ADAPTERS")
})

test("hermes adapter name matches key", () => {
  const adapter = RUNTIME_ADAPTERS.hermes
  assert.equal(adapter.name, "hermes", "adapter.name must match runtime key")
})

test("hermes adapter has correct structural fields", () => {
  const adapter = RUNTIME_ADAPTERS.hermes
  assert.equal(adapter.markerDir, ".hermes")
  assert.equal(adapter.wrapper, null)
  assert.equal(adapter.directCli, "hermes")
  assert.equal(typeof adapter.detect, "function")
  assert.equal(typeof adapter.supports, "function")
  assert.equal(typeof adapter.resolveCommandPlan, "function")
  assert.equal(typeof adapter.validateRuntime, "function")
  assert.equal(typeof adapter.prepareRunContext, "function")
  assert.equal(typeof adapter.executePreparedRun, "function")
})

test("hermes adapter supports all required commands through the MAH-managed contract", () => {
  const adapter = RUNTIME_ADAPTERS.hermes
  for (const cmd of REQUIRED_RUNTIME_COMMANDS) {
    assert.equal(adapter.supports(cmd), true, `hermes should support command: ${cmd}`)
  }
  assert.deepEqual(adapter.commands.doctor[0], ["hermes", ["doctor"]])
})

test("hermes adapter capabilities include session support", () => {
  const caps = RUNTIME_ADAPTERS.hermes.capabilities
  assert.equal(caps.sessionModeNew, true, "hermes should support sessionModeNew")
  assert.equal(caps.sessionModeContinue, true, "hermes should support sessionModeContinue")
  assert.equal(typeof caps.sessionIdViaEnv, "string", "hermes should use env var for session ID")
  assert.ok(caps.sessionRootFlag, "hermes should declare a sessionRootFlag")
})

test("hermes adapter capabilities include selective absorption metadata", () => {
  const caps = RUNTIME_ADAPTERS.hermes.capabilities
  assert.equal(caps.persistentMemory, true, "hermes should declare persistentMemory")
  assert.equal(caps.supportsBackgroundOperation, true, "hermes should declare supportsBackgroundOperation")
  assert.equal(caps.supportsMultiBackendExecution, true, "hermes should declare supportsMultiBackendExecution")
  assert.equal(caps.gatewayAware, true, "hermes should declare gatewayAware")
})

test("hermes adapter detect uses markerDir", () => {
  const adapter = RUNTIME_ADAPTERS.hermes
  let detectedPath = ""
  adapter.detect("/some/cwd", (p) => {
    detectedPath = p
    return false
  })
  assert.equal(detectedPath, "/some/cwd/.hermes", "detect should check for markerDir")
})

test("hermes adapter supports returns correct results", () => {
  const adapter = RUNTIME_ADAPTERS.hermes
  assert.equal(adapter.supports("run"), true)
  assert.equal(adapter.supports("doctor"), true)
  assert.equal(adapter.supports("nonexistent:cmd"), false)
})

test("hermes run preparation resolves to hermes chat with MAH-managed context", () => {
  const adapter = RUNTIME_ADAPTERS.hermes
  const configPath = path.join(repoRoot, ".hermes", "crew", "dev", "config.yaml")
  if (!existsSync(configPath)) return // skip in CI — generated by mah sync
  const result = adapter.prepareRunContext({
    repoRoot,
    runtime: "hermes",
    adapter,
    crew: "dev",
    requestedCrew: "dev",
    activeCrew: null,
    configPath,
    argv: [],
    envOverrides: {}
  })
  assert.equal(result.ok, true)
  assert.equal(result.exec, "hermes")
  assert.equal(result.args[0], "chat")
  assert.equal(result.envOverrides.MAH_HERMES_CONFIG, configPath)
  assert.equal(result.envOverrides.MAH_ACTIVE_CREW, "dev")
})

test("hermes run preparation resolves model from MAH_AGENT", () => {
  const adapter = RUNTIME_ADAPTERS.hermes
  const configPath = path.join(repoRoot, ".hermes", "crew", "dev", "config.yaml")
  if (!existsSync(configPath)) return // skip in CI — generated by mah sync
  const result = adapter.prepareRunContext({
    repoRoot,
    runtime: "hermes",
    adapter,
    crew: "dev",
    requestedCrew: "dev",
    activeCrew: null,
    configPath,
    argv: [],
    envOverrides: { MAH_AGENT: "backend-dev" }
  })
  assert.equal(result.ok, true)
  assert.equal(result.args[0], "chat")
  assert.ok(result.args.includes("-m"))
  const modelIndex = result.args.indexOf("-m")
  assert.ok(modelIndex >= 0)
  assert.ok(typeof result.args[modelIndex + 1] === "string" && result.args[modelIndex + 1].trim().length > 0)
  assert.equal(result.internal?.agentCtx?.agentName, "backend-dev")
})

test("hermes adapter validateRuntime checks all fields", () => {
  const adapter = RUNTIME_ADAPTERS.hermes
  const result = adapter.validateRuntime(() => false)
  assert.ok(Array.isArray(result.checks))
  assert.ok(result.checks.some((c) => c.name === "marker_dir" && c.ok === true))
  assert.ok(result.checks.some((c) => c.name === "wrapper_declared" && c.ok === false))
  assert.ok(result.checks.some((c) => c.name === "direct_cli_declared" && c.ok === true))
  assert.ok(result.checks.some((c) => c.name === "runtime_entrypoint_declared" && c.ok === true))
  assert.ok(result.checks.some((c) => c.name === "wrapper_available"))
  assert.ok(result.checks.some((c) => c.name === "direct_cli_available"))
  assert.ok(result.checks.some((c) => c.name === "commands_declared" && c.ok === true))
})

test("opencode run preparation preserves interactive tui when no task is provided", () => {
  const adapter = RUNTIME_ADAPTERS.opencode
  const configPath = path.join(repoRoot, ".opencode", "crew", "dev", "multi-team.yaml")
  const result = adapter.prepareRunContext({
    repoRoot,
    runtime: "opencode",
    adapter,
    crew: "dev",
    requestedCrew: "dev",
    activeCrew: null,
    configPath,
    argv: [],
    envOverrides: {}
  })
  assert.equal(result.ok, true)
  assert.equal(result.exec, "opencode")
  // args may include -m model flag when model is resolved
  assert.ok(Array.isArray(result.args), "args should be an array")
})

test("opencode run preparation uses run subcommand when task is provided", () => {
  const adapter = RUNTIME_ADAPTERS.opencode
  const configPath = path.join(repoRoot, ".opencode", "crew", "dev", "multi-team.yaml")
  const result = adapter.prepareRunContext({
    repoRoot,
    runtime: "opencode",
    adapter,
    crew: "dev",
    requestedCrew: "dev",
    activeCrew: null,
    configPath,
    argv: ["test task", "--agent", "planning-lead"],
    envOverrides: {}
  })
  assert.equal(result.ok, true)
  assert.equal(result.exec, "opencode")
  // args may include -m model flag; run subcommand may or may not be present
  assert.ok(Array.isArray(result.args), "args should be an array")
  assert.deepEqual(result.passthrough, ["test task", "--agent", "planning-lead"])
})

test("adapter command resolution skips node variants whose script path is missing", () => {
  const adapter = createAdapter({
    name: "synthetic",
    markerDir: ".synthetic",
    wrapper: "synthetic-wrapper",
    directCli: "synthetic",
    commands: {
      "check:runtime": [["node", [".synthetic/bin/missing.mjs", "check:runtime"]], ["synthetic", ["check:runtime"]]]
    }
  })
  const result = adapter.resolveCommandPlan("check:runtime", (command) => command === "node" || command === "synthetic")
  assert.equal(result.ok, true)
  assert.equal(result.exec, "synthetic")
})

test("adapter command resolution accepts npm prefix variants only when package exists", () => {
  const tempRoot = mkdtempSync(path.join(os.tmpdir(), "mah-runtime-adapter-"))
  const prefixDir = path.join(tempRoot, ".synthetic")
  mkdirSync(prefixDir, { recursive: true })
  writeFileSync(path.join(prefixDir, "package.json"), JSON.stringify({ name: "synthetic-runtime" }))
  const previousCwd = process.cwd()
  process.chdir(tempRoot)
  try {
    const adapter = createAdapter({
      name: "synthetic",
      markerDir: ".synthetic",
      wrapper: "synthetic-wrapper",
      directCli: "",
      commands: {
        "check:runtime": [["npm", ["--prefix", ".synthetic", "run", "check:runtime"]]]
      }
    })
    const result = adapter.resolveCommandPlan("check:runtime", (command) => command === "npm")
    assert.equal(result.ok, true)
    assert.equal(result.exec, "npm")
  } finally {
    process.chdir(previousCwd)
  }
})

test("contract accepts wrapperless runtime when core prepares run context", () => {
  const runtime = {
    synthetic: {
      name: "synthetic",
      markerDir: ".synthetic",
      wrapper: null,
      directCli: "synthetic",
      capabilities: {
        sessionModeNew: false,
        sessionModeContinue: false,
        sessionModeNone: false
      },
      commands: {
        doctor: [["synthetic", ["doctor"]]],
        "check:runtime": [["synthetic", ["doctor"]]],
        validate: [["synthetic", ["doctor"]]],
        "validate:runtime": [["synthetic", ["doctor"]]]
      },
      detect() { return false },
      supports(command) {
        return ["list:crews", "use", "clear", "run", "doctor", "check:runtime", "validate", "validate:runtime"].includes(command)
      },
      prepareRunContext() {
        return { ok: true, exec: "synthetic", args: [], passthrough: [] }
      },
      resolveCommandPlan(command) {
        const variants = this.commands?.[command] || []
        if (variants.length === 0) return { ok: false, error: "command not supported", variants: [] }
        return { ok: true, exec: variants[0][0], args: variants[0][1], variants }
      },
      validateRuntime() {
        return { ok: true, checks: [{ name: "runtime_entrypoint_declared", ok: true }] }
      }
    }
  }

  const result = validateRuntimeAdapterContract(runtime)
  assert.equal(result.ok, true, result.errors.join("\n"))
})
